export const products = [
  {
    name: "AeroSport",
    code: "AEROSPORT",
    image: "./product-1.png",
    prices: [{ price: 359.00, salePrice: null }],
    category: "Watch",
    quantity: 0,
  },
  {
    name: "ApexGuard",
    code: "APEXGUARD",
    image: "./product-2.png",
    prices: [{ price: 429.00, salePrice: 399.00 }],
    category: "Watch",
    quantity: 0,
  },
  {
    name: "Canyon Harmony",
    code: "CANYON HARMONY",
    image: "./product-3.png",
    prices: [{ price: 59.00, salePrice: 49.00 }],
    category: "Bracelet",
    quantity: 0,
  },
  {
    name: "ChronoTrigger",
    code: "CHRONOTRIGGER",
    image: "./product-4.png",
    prices: [{ price: 679.00, salePrice: null }],
    category: "Watch",
    quantity: 0,
  },
  {
    name: "DigitalEdge",
    code: "DIGITALEDGE",
    image: "./product-5.png",
    prices: [{ price: 489.00, salePrice: null }],
    category: "Smartwatch",
    quantity: 0,
  },
  {
    name: "DynaChrono",
    code: "DYNACHRONO",
    image: "./product-6.png",
    prices: [{ price: 459.00, salePrice: null }],
    category: "Watch",
    quantity: 0,
  },
  {
    name: "Flare Glaciers",
    code: "FLARE GLACIERS",
    image: "./product-7.png",
    prices: [{ price: 149.00, salePrice: null }],
    category: "Glasses",
    quantity: 0,
  },
  {
    name: "Galactic Gazers",
    code: "GALACTIC GAZERS",
    image: "./product-8.png",
    prices: [{ price: 129.00, salePrice: 99.00 }],
    category: "Glasses",
    quantity: 0,
  },
  {
    name: "Leather Band",
    code: "LEATHER BAND",
    image: "./product-9.png",
    prices: [{ price: 79.00, salePrice: null }],
    category: "Bracelet",
    quantity: 0,
  },
  {
    name: "Metro Shadows",
    code: "METRO SHADOWS",
    image: "./product-10.png",
    prices: [{ price: 99.00, salePrice: null }],
    category: "Glasses",
    quantity: 0,
  },
  {
    name: "Mirage Dunes",
    code: "MIRAGE DUNES",
    image: "./product-11.png",
    prices: [{ price: 79.00, salePrice: null }],
    category: "Glasses",
    quantity: 0,
  },
  {
    name: "Noble Crest",
    code: "NOBLE CREST",
    image: "./product-12.png",
    prices: [{ price: 129.00, salePrice: null }],
    category: "Bracelet",
    quantity: 0,
  },
  {
    name: "PrestigeHorizons",
    code: "PRESTIGEHORIZONS",
    image: "./product-13.png",
    prices: [{ price: 379.00, salePrice: 319.00 }],
    category: "Watch",
    quantity: 0,
  },
  {
    name: "Rustic Rhythm",
    code: "RUSTIC RHYTHM",
    image: "./product-14.png",
    prices: [{ price: 79.00, salePrice: null }],
    category: "Bracelet",
    quantity: 0,
  },
  {
    name: "SmartSync",
    code: "SMARTSYNC",
    image: "./product-15.png",
    prices: [{ price: 289.00, salePrice: null }],
    category: "Smartwatch",
    quantity: 0,
  },
  {
    name: "Spartan Chain",
    code: "SPARTAN CHAIN",
    image: "./product-16.png",
    prices: [{ price: 359.00, salePrice: 329.00 }],
    category: "Bracelet",
    quantity: 0,
  },
  {
    name: "Sport Luxe",
    code: "SPORT LUXE",
    image: "./product-17.png",
    prices: [{ price: 249.00, salePrice: 199.00 }],
    category: "Glasses",
    quantity: 0,
  },
  {
    name: "Tribal Wristlet",
    code: "TRIBAL WRISTLET",
    image: "./product-18.png",
    prices: [{ price: 189.00, salePrice: null }],
    category: "Bracelet",
    quantity: 0,
  },
  {
    name: "UrbanLuxury",
    code: "URBANLUXURY",
    image: "./product-19.png",
    prices: [{ price: 279.00, salePrice: null }],
    category: "Watch",
    quantity: 0,
  },
  {
    name: "Vanguard Tints",
    code: "VANGUARD TINTS",
    image: "./product-20.png",
    prices: [{ price: 179.00, salePrice: null }],
    category: "Glasses",
    quantity: 0,
  },
];

